sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5t5fcUfsJnmMgPUVwmdm
    access-key-secret: 1xiEgna0qYiNiobUXTmuvuI2O7k3lQ
    bucket-name: takeout-24
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    database: 0